# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFirebase-desktop' do

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
#pod 'FirebaseDatabase'

end

target 'TestFirebase-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFirebase-mobile

end
